---
# master_setup.yml
- import_playbook: 1_install_packages.yml
- import_playbook: 2_build_pbs.yml
- import_playbook: 3_post_install.yml
- import_playbook: 4_update_conf.yml
- import_playbook: 5_start_pbs.yml
- import_playbook: 6_add_compute_nodes.yml
