---
- name: Update Slurm configuration and restart services if needed
  hosts: all
  become: true

  tasks:
    - name: Update slurm.conf
      copy:
        src: ./slurm.conf
        dest: /etc/slurm/slurm.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart Slurm

  handlers:
    - name: Restart Slurm
      systemd:
        name: "{{ 'slurmctld' if inventory_hostname in groups['control'] else 'slurmd' }}"
        state: restarted
